### ISSUE TITLE
Dyson Brownian Motion and extended airy process

### ISSUE THREAD

**Issue by lovvge** [mitmath/18338#8]
have code for the demonstration.

**Comment by dkonomis-zz** [comment]
Claiming this project.

**Comment by alanedelman** [comment]
i would start with adding two GUE's
and doing an extended Airy process with two time points

for example, from https://www.emis.de/journals/EJP-ECP/article/download/1074/1074-3531-1-PB.pdf
take m=2 in Section II

**Comment by alanedelman** [comment]
add to dimitris notebook
